[workspace]

members = [
    "crates/chessatiel",
    "crates/guts",
    "crates/brain",
    "crates/beak",
]

[profile.release]
lto = "thin"
debug = true

[profile.bench]
lto = "thin"
debug = true
