[workspace]

members = [
    "crates/brain",
    "crates/chessatiel",
    "crates/guts",
]

[profile.release]
lto = "thin"
debug = true

[profile.dev]
opt-level = 1

[profile.bench]
lto = "thin"
debug = true
