[package]
name = "guts"
version = "0.1.0"
authors = ["Tim Evers <29369097+TVerse@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.25"

[dev-dependencies]
paste = "1.0.5"
criterion = { version = "0.3", features = ["html_reports"] }

#[[bench]]
#name = "perft"
#harness = false
