[package]
name = "beak"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.2.1"
thiserror = "1.0.25"
guts = { path = "../guts" }
itertools = "0.10.1"