[package]
name = "chessatiel"
version = "0.1.0"
authors = ["Tim Evers <29369097+TVerse@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guts = { path = "../guts" }
beak = { path = "../beak" }
brain = { path = "../brain" }

log = "0.4.14"
stderrlog = "0.5.1"
structopt = "0.3.21"