[package]
name = "brain"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
guts = { path = "../guts" }
log = "0.4.17"
once_cell = "1.13.0"
tokio = { version = "1.20.0" }

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "search"
harness = false
